### ISSUE TITLE
Example is broken

### ISSUE THREAD

**Issue by zcsahok** [lpodkalicki/attiny-onewire-library#1]
Example got broken in 2525952aead5: `onewire_*()` functions require a pin mask (e.g. _BV(PB2)) but they are called with pin number (PB2).

**Comment by lpodkalicki** [comment]
Ouch. You're right. I have been testing it for PB0. So, that's why tests passed.

Thank you for reporting it. I have added a fix for pin masking (https://github.com/lpodkalicki/attiny-onewire-library/commit/33d448139ab299ef991e9944ba00b7eee2d30de3)

**Comment by zcsahok** [comment]
Thanks for the fix!
